// Code generated by MockGen. DO NOT EDIT.
// Source: api.go

// Package liquidity is a generated GoMock package.
package liquidity

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	liquidity "github.com/bnb-chain/zkbas/common/model/liquidity"
)

// MockLiquidityModel is a mock of LiquidityModel interface.
type MockLiquidityModel struct {
	ctrl     *gomock.Controller
	recorder *MockLiquidityModelMockRecorder
}

// MockLiquidityModelMockRecorder is the mock recorder for MockLiquidityModel.
type MockLiquidityModelMockRecorder struct {
	mock *MockLiquidityModel
}

// NewMockLiquidityModel creates a new mock instance.
func NewMockLiquidityModel(ctrl *gomock.Controller) *MockLiquidityModel {
	mock := &MockLiquidityModel{ctrl: ctrl}
	mock.recorder = &MockLiquidityModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLiquidityModel) EXPECT() *MockLiquidityModelMockRecorder {
	return m.recorder
}

// GetAllLiquidityAssets mocks base method.
func (m *MockLiquidityModel) GetAllLiquidityAssets() ([]*liquidity.Liquidity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLiquidityAssets")
	ret0, _ := ret[0].([]*liquidity.Liquidity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllLiquidityAssets indicates an expected call of GetAllLiquidityAssets.
func (mr *MockLiquidityModelMockRecorder) GetAllLiquidityAssets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLiquidityAssets", reflect.TypeOf((*MockLiquidityModel)(nil).GetAllLiquidityAssets))
}

// GetLiquidityByPairIndex mocks base method.
func (m *MockLiquidityModel) GetLiquidityByPairIndex(pairIndex int64) (*liquidity.Liquidity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLiquidityByPairIndex", pairIndex)
	ret0, _ := ret[0].(*liquidity.Liquidity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLiquidityByPairIndex indicates an expected call of GetLiquidityByPairIndex.
func (mr *MockLiquidityModelMockRecorder) GetLiquidityByPairIndex(pairIndex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLiquidityByPairIndex", reflect.TypeOf((*MockLiquidityModel)(nil).GetLiquidityByPairIndex), pairIndex)
}
