// Code generated by goctl. DO NOT EDIT!
// Source: committer.proto

package committer

import (
	"context"
	"github.com/zecrey-labs/zecrey-legend/service/rpc/committer/committerProto"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = committerProto.Request
	Response = committerProto.Response

	Committer interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultCommitter struct {
		cli zrpc.Client
	}
)

func NewCommitter(cli zrpc.Client) Committer {
	return &defaultCommitter{
		cli: cli,
	}
}

func (m *defaultCommitter) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := committerProto.NewCommitterClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
