// Code generated by goctl. DO NOT EDIT!
// Source: l2BlockMonitor.proto

package server

import (
	"context"
	"github.com/zecrey-labs/zecrey-legend/service/cronjob/l2BlockMonitor/internal/logic"
	"github.com/zecrey-labs/zecrey-legend/service/cronjob/l2BlockMonitor/internal/svc"
	l2BlockMonitor2 "github.com/zecrey-labs/zecrey-legend/service/cronjob/l2BlockMonitor/l2BlockMonitor"
)

type L2BlockMonitorServer struct {
	svcCtx *svc.ServiceContext
	l2BlockMonitor2.UnimplementedL2BlockMonitorServer
}

func NewL2BlockMonitorServer(svcCtx *svc.ServiceContext) *L2BlockMonitorServer {
	return &L2BlockMonitorServer{
		svcCtx: svcCtx,
	}
}

func (s *L2BlockMonitorServer) Ping(ctx context.Context, in *l2BlockMonitor2.Request) (*l2BlockMonitor2.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
