// Code generated by goctl. DO NOT EDIT!
// Source: proverHub.proto

package server

import (
	"context"

	"github.com/zecrey-labs/zecrey-legend/service/rpc/proverHub/internal/logic"
	"github.com/zecrey-labs/zecrey-legend/service/rpc/proverHub/internal/svc"
	"github.com/zecrey-labs/zecrey-legend/service/rpc/proverHub/proverHubProto"
)

type ProverHubRPCServer struct {
	svcCtx *svc.ServiceContext
	proverHubProto.UnimplementedProverHubRPCServer
}

func NewProverHubRPCServer(svcCtx *svc.ServiceContext) *ProverHubRPCServer {
	return &ProverHubRPCServer{
		svcCtx: svcCtx,
	}
}

func (s *ProverHubRPCServer) GetUnprovedBlock(ctx context.Context, in *proverHubProto.ReqGetUnprovedBlock) (*proverHubProto.RespGetUnprovedBlock, error) {
	l := logic.NewGetUnprovedBlockLogic(ctx, s.svcCtx)
	return l.GetUnprovedBlock(in)
}

func (s *ProverHubRPCServer) SubmitProof(ctx context.Context, in *proverHubProto.ReqSubmitProof) (*proverHubProto.RespSubmitProof, error) {
	l := logic.NewSubmitProofLogic(ctx, s.svcCtx)
	return l.SubmitProof(in)
}
