// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: governanceMonitor.proto

package governanceMonitor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GovernanceMonitorClient is the client API for GovernanceMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GovernanceMonitorClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type governanceMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewGovernanceMonitorClient(cc grpc.ClientConnInterface) GovernanceMonitorClient {
	return &governanceMonitorClient{cc}
}

func (c *governanceMonitorClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/governanceMonitor.GovernanceMonitor/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GovernanceMonitorServer is the server API for GovernanceMonitor service.
// All implementations must embed UnimplementedGovernanceMonitorServer
// for forward compatibility
type GovernanceMonitorServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGovernanceMonitorServer()
}

// UnimplementedGovernanceMonitorServer must be embedded to have forward compatible implementations.
type UnimplementedGovernanceMonitorServer struct {
}

func (UnimplementedGovernanceMonitorServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGovernanceMonitorServer) mustEmbedUnimplementedGovernanceMonitorServer() {}

// UnsafeGovernanceMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GovernanceMonitorServer will
// result in compilation errors.
type UnsafeGovernanceMonitorServer interface {
	mustEmbedUnimplementedGovernanceMonitorServer()
}

func RegisterGovernanceMonitorServer(s grpc.ServiceRegistrar, srv GovernanceMonitorServer) {
	s.RegisterService(&GovernanceMonitor_ServiceDesc, srv)
}

func _GovernanceMonitor_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernanceMonitorServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/governanceMonitor.GovernanceMonitor/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernanceMonitorServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GovernanceMonitor_ServiceDesc is the grpc.ServiceDesc for GovernanceMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GovernanceMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "governanceMonitor.GovernanceMonitor",
	HandlerType: (*GovernanceMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GovernanceMonitor_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "governanceMonitor.proto",
}
