// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mempoolmonitor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MempoolMonitorClient is the client API for MempoolMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MempoolMonitorClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type mempoolMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewMempoolMonitorClient(cc grpc.ClientConnInterface) MempoolMonitorClient {
	return &mempoolMonitorClient{cc}
}

func (c *mempoolMonitorClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/mempoolMonitor.MempoolMonitor/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MempoolMonitorServer is the server API for MempoolMonitor service.
// All implementations must embed UnimplementedMempoolMonitorServer
// for forward compatibility
type MempoolMonitorServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedMempoolMonitorServer()
}

// UnimplementedMempoolMonitorServer must be embedded to have forward compatible implementations.
type UnimplementedMempoolMonitorServer struct {
}

func (UnimplementedMempoolMonitorServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMempoolMonitorServer) mustEmbedUnimplementedMempoolMonitorServer() {}

// UnsafeMempoolMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MempoolMonitorServer will
// result in compilation errors.
type UnsafeMempoolMonitorServer interface {
	mustEmbedUnimplementedMempoolMonitorServer()
}

func RegisterMempoolMonitorServer(s grpc.ServiceRegistrar, srv MempoolMonitorServer) {
	s.RegisterService(&MempoolMonitor_ServiceDesc, srv)
}

func _MempoolMonitor_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MempoolMonitorServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mempoolMonitor.MempoolMonitor/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MempoolMonitorServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MempoolMonitor_ServiceDesc is the grpc.ServiceDesc for MempoolMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MempoolMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mempoolMonitor.MempoolMonitor",
	HandlerType: (*MempoolMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _MempoolMonitor_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mempoolmonitor.proto",
}
