package multcache

import (
	"errors"

	"github.com/zecrey-labs/zecrey-legend/pkg/zerror"
)

// error got from other package
var (
	errRedisCacheKeyNotExist = errors.New("redis: nil")
	errGoCacheKeyNotExist    = errors.New("Value not found in GoCache store")
)

// error generated by multcache
var (
	ErrNotExistInSql = zerror.New(40001, "data not exist in sql")
)

// cache key register
const (
	KeyExample = "cache:dataName_dataIdentity"
	// account
	KeyAccountAccountName = "cache:account_accountName"

	KeyGetBlockByBlockHeight   = "cache:block_blockHeight"
	KeyGetBlockBlockCommitment = "cache::block:blockCommitment:"
	KeyGetBlockWithTxHeight    = "cache::block:blockHeightWithTx:"
	KeyGetBlockList            = "cache::block:blockList:"
)
