// Code generated by goctl. DO NOT EDIT!
// Source: governanceMonitor.proto

package server

import (
	"context"

	"github.com/zecrey-labs/zecrey-legend/service/cronjob/blockMonitor/blockMonitor"
	"github.com/zecrey-labs/zecrey-legend/service/cronjob/blockMonitor/internal/logic"
	"github.com/zecrey-labs/zecrey-legend/service/cronjob/blockMonitor/internal/svc"
)

type BlockMonitorServer struct {
	svcCtx *svc.ServiceContext
	blockMonitor.UnimplementedBlockMonitorServer
}

func NewBlockMonitorServer(svcCtx *svc.ServiceContext) *BlockMonitorServer {
	return &BlockMonitorServer{
		svcCtx: svcCtx,
	}
}

func (s *BlockMonitorServer) Ping(ctx context.Context, in *blockMonitor.Request) (*blockMonitor.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
