// Code generated by goctl. DO NOT EDIT.
package types

type ReqGetStatus struct {
}

type RespGetStatus struct {
	Status        uint32 `json:"status"`
	NetworkId     uint32 `json:"network_id"`
	ServerVersion string `json:"server_version"`
}

type AccountAsset struct {
	AssetId                  uint32 `json:"asset_id"`
	Balance                  string `json:"balance"`
	LpAmount                 string `json:"lp_amount"`
	OfferCanceledOrFinalized string `json:"offer_canceled_or_finalized"`
}

type ReqGetAccountInfoByPubKey struct {
	AccountPk string `form:"account_pk"`
}

type RespGetAccountInfoByPubKey struct {
	AccountStatus uint32          `json:"account_status"`
	AccountName   string          `json:"account_name"`
	AccountIndex  int64           `json:"account_index"`
	Assets        []*AccountAsset `json:"assets"`
}

type ReqGetAccountInfoByAccountIndex struct {
	AccountIndex int64 `json:"account_index"`
}

type RespGetAccountInfoByAccountIndex struct {
	AccountStatus uint32          `json:"account_status"`
	AccountName   string          `json:"account_name"`
	AccountPk     string          `form:"account_pk"`
	Assets        []*AccountAsset `json:"assets"`
}

type ReqGetAccountStatusByAccountName struct {
	AccountName string `form:"account_name"`
}

type RespGetAccountStatusByAccountName struct {
	AccountStatus uint32 `json:"account_status"`
	AccountIndex  uint32 `json:"account_index"`
	AccountPk     string `json:"account_pk"`
}

type ReqGetAccountInfoByAccountName struct {
	AccountName string `form:"account_name"`
}

type RespGetAccountInfoByAccountName struct {
	AccountIndex uint32          `json:"account_index"`
	AccountPk    string          `json:"account_pk"`
	Assets       []*AccountAsset `json:"assets"`
}

type ReqGetBlanceByAssetIdAndAccountName struct {
	AssetId     uint32 `form:"asset_id"`
	AccountName string `form:"account_name"`
}

type RespGetBlanceInfoByAssetIdAndAccountName struct {
	Balance string `json:"balance_enc"`
}

type ReqGetAssetsByAccountName struct {
	AccountName string `form:"account_name"`
}

type RespGetAssetsByAccountName struct {
	Assets []*AccountAsset `json:"assets"`
}

type ReqGetAccountLiquidityPairsByAccountIndex struct {
	AccountIndex uint32 `form:"account_index"`
}

type AccountLiquidityPairs struct {
	PairIndex   uint32 `json:"pair_index"`
	AssetAId    uint32 `json:"asset_a_id"`
	AssetAName  string `json:"asset_a_name"`
	AssetBId    uint32 `json:"asset_b_id"`
	AssetBName  string `json:"asset_b_name"`
	LpAmountEnc string `json:"lp_amount_enc"`
	CreatedAt   int64  `json:"created_at"`
}

type RespGetAccountLiquidityPairsByAccountIndex struct {
	Pairs []*AccountLiquidityPairs `json:"pairs"`
}

type TxHash struct {
	TxHash    string `json:"tx_hash"`
	CreatedAt int64  `json:"created_at"`
}

type Block struct {
	BlockCommitment                 string `json:"block_commitment"`
	BlockHeight                     int64  `json:"block_height"`
	StateRoot                       string `json:"state_root"`
	PriorityOperations              int64  `json:"priority_operations"`
	PendingOnChainOperationsHash    string `json:"pending_on_chain_operations_hash"`
	PendingOnChainOperationsPubData string `json:"pending_on_chain_operations_hub_data"`
	CommittedTxHash                 string `json:"committed_tx_hash"`
	CommittedAt                     int64  `json:"committed_at"`
	VerifiedTxHash                  string `json:"verified_tx_hash"`
	VerifiedAt                      int64  `json:"verified_at"`
	Txs                             []*Tx  `json:"txs"`
	BlockStatus                     int64  `json:"block_status"`
}

type ReqGetBlocks struct {
	Offset uint16 `form:"offset"`
	Limit  uint16 `form:"limit"`
}

type RespGetBlocks struct {
	Total  uint32   `json:"total"`
	Blocks []*Block `json:"blocks"`
}

type ReqGetBlockByCommitment struct {
	BlockCommitment string `form:"block_commitment"`
}

type RespGetBlockByCommitment struct {
	Block Block `json:"block"`
}

type ReqGetBlockByBlockHeight struct {
	BlockHeight uint64 `form:"block_height"`
}

type RespGetBlockByBlockHeight struct {
	Block Block `json:"block"`
}

type ReqGetLayer2BasicInfo struct {
}

type RespGetLayer2BasicInfo struct {
	BlockCommitted             int64    `json:"block_committed"`
	BlockVerified              int64    `json:"block_verified"`
	TotalTransactions          int64    `json:"total_transactions"`
	TransactionsCountYesterday int64    `json:"transactions_count_yesterday"`
	TransactionsCountToday     int64    `json:"transactions_count_today"`
	DauYesterday               int64    `json:"dau_yesterday"`
	DauToday                   int64    `json:"dau_today"`
	ContractAddresses          []string `json:"contract_addresses"`
}

type ReqGetAssetsList struct {
}

type AssetInfo struct {
	AssetId       uint32 `json:"asset_id"`
	AssetName     string `json:"asset_name"`
	AssetDecimals uint32 `json:"asset_decimals"`
	AssetSymbol   string `json:"asset_symbol"`
	AssetAddress  string `json:"asset_address"`
}

type RespGetAssetsList struct {
	Assets []*AssetInfo `json:"assets"`
}

type ReqGetCurrencyPriceBySymbol struct {
	Symbol string `form:"symbol"`
}

type RespGetCurrencyPriceBySymbol struct {
	AssetId uint32 `json:"assetId"`
	Price   uint64 `json:"price"`
}

type ReqGetCurrencyPrices struct {
}

type DataCurrencyPrices struct {
	Pair    string `json:"pair"`
	AssetId uint32 `json:"assetId"`
	Price   uint64 `json:"price"`
}

type RespGetCurrencyPrices struct {
	Data []*DataCurrencyPrices `json:"data"`
}

type ReqGetGasFee struct {
	AssetId uint32 `form:"asset_id"`
}

type RespGetGasFee struct {
	GasFee uint64 `json:"gas_fee"`
}

type ReqGetWithdrawGasFee struct {
	AssetId         uint32 `form:"asset_id"`
	WithdrawAssetId uint32 `form:"withdraw_asset_id"`
	WithdrawAmount  uint64 `form:"withdraw_amount"`
}

type RespGetWithdrawGasFee struct {
	WithdrawGasFee uint64 `json:"withdraw_gas_fee"`
}

type ReqGetAccounts struct {
	Offset uint16 `form:"offset" validator:"min=0"`
	Limit  uint16 `form:"limit" validator:"min=0,max=50"`
}

type Accounts struct {
	AccountIndex uint32 `json:"account_index"`
	AccountName  string `json:"account_name"`
	PublicKey    string `json:"public_key"`
}

type RespGetAccounts struct {
	Total    uint32      `json:"total"`
	Accounts []*Accounts `json:"accounts"`
}

type ReqSearch struct {
	Info string `form:"info"`
}

type RespSearch struct {
	DataType int32 `json:"data_type"`
}

type ReqGetSwapAmount struct {
	PairIndex   uint32 `form:"pair_index"`
	AssetId     uint32 `form:"asset_id"`
	AssetAmount string `form:"asset_amount"`
	IsFrom      bool   `form:"is_from"`
}

type RespGetSwapAmount struct {
	ResAssetAmount string `json:"res_asset_amount"`
	ResAssetId     uint32 `json:"res_asset_id"`
}

type ReqGetAvailablePairs struct {
}

type Pair struct {
	PairIndex    uint32 `json:"pair_index"`
	AssetAId     uint32 `json:"asset_a_id"`
	AssetAName   string `json:"asset_a_name"`
	AssetAAmount string `json:"asset_a_amount"`
	AssetBId     uint32 `json:"asset_b_id"`
	AssetBName   string `json:"asset_b_name"`
	AssetBAmount string `json:"asset_b_amount"`
	FeeRate      int64  `json:"fee_Rate"`
	TreasuryRate int64  `json:"treasury_rate"`
}

type RespGetAvailablePairs struct {
	Pairs []*Pair `json:"result"`
}

type ReqGetLPValue struct {
	PairIndex uint32 `form:"pair_index"`
	LpAmount  string `form:"lp_amount"`
}

type RespGetLPValue struct {
	AssetAId     uint32 `json:"asset_a_id"`
	AssetAName   string `json:"asset_a_name"`
	AssetAAmount string `json:"asset_a_amount"`
	AssetBid     uint32 `json:"asset_b_id"`
	AssetBName   string `json:"asset_b_name"`
	AssetBAmount string `json:"asset_b_amount"`
}

type ReqGetPairInfo struct {
	PairIndex uint32 `form:"pair_index"`
}

type RespGetPairInfo struct {
	AssetAId      uint32 `json:"asset_a_id"`
	AssetAAmount  string `json:"asset_a_amount"`
	AssetBId      uint32 `json:"asset_b_id"`
	AssetBAmount  string `json:"asset_b_amount"`
	TotalLpAmount string `json:"total_lp_amount"`
}

type TxDetail struct {
	TxId            int64  `json:"tx_id"`
	AssetId         int64  `json:"asset_id"`
	AssetType       int64  `json:"asset_type"`
	AccountIndex    int64  `json:"account_index"`
	AccountName     string `json:"account_name"`
	AccountBalance  string `json:"accountBalance"`
	AccountDelta    string `json:"accountDelta"`
	Order           int64  `json:"order"`
	AccountOrder    int64  `json:"account_order"`
	Nonce           int64  `json:"nonce"`
	CollectionNonce int64  `json:"collection_nonce"`
}

type Tx struct {
	TxHash        string      `json:"tx_hash"`
	TxType        int64       `json:"tx_type,range=[1:64]"`
	TxAmount      string      `json:"tx_amount"`
	TxInfo        string      `json:"tx_info"`
	TxDetails     []*TxDetail `json:"tx_details"`
	TxStatus      int64       `json:"tx_status"`
	GasFeeAssetId int64       `json:"gas_fee_asset_id"`
	GasFee        string      `json:"gas_fee"`
	NftIndex      int64       `json:"nft_index"`
	PairIndex     int64       `json:"pair_index"`
	AssetId       int64       `json:"asset_id"`
	NativeAddress string      `json:"native_adress"`
	ExtraInfo     string      `json:"extra_info"`
	Memo          string      `json:"memo"`
	AccountIndex  int64       `json:"account_index"`
	Nonce         int64       `json:"nonce"`
	ExpiredAt     int64       `json:"expire_at"`
	Status        int64       `json:"status,options=0|1|2"`
	BlockId       int64       `json:"block_id"`
	BlockHeight   int64       `json:"block_height"`
	CreatedAt     int64       `json:"created_at"`
	StateRoot     string      `json:"state_root"`
}

type TxAccount struct {
	AccountIndex   uint32 `json:"account_index"`
	AccountName    string `json:"account_name"`
	AccountBalance string `json:"account_balance"`
	AccountDelta   string `json:"account_delta"`
}

type ReqGetTxsListByBlockHeight struct {
	BlockHeight uint64 `form:"block_height"`
	Limit       uint16 `form:"limit"`
	Offset      uint16 `form:"offset"`
}

type RespGetTxsListByBlockHeight struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"txs"`
}

type ReqGetTxsListByAccountIndex struct {
	AccountIndex uint32 `form:"account_index"`
	Offset       uint16 `form:"offset"`
	Limit        uint16 `form:"limit"`
}

type RespGetTxsListByAccountIndex struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"txs"`
}

type ReqGetTxsByAccountIndexAndTxType struct {
	AccountIndex uint32 `form:"account_index"`
	TxType       uint32 `form:"tx_type"`
	Offset       uint32 `form:"offset"`
	Limit        uint32 `form:"limit"`
}

type RespGetTxsByAccountIndexAndTxType struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"txs"`
}

type ReqGetTxsByAccountName struct {
	AccountName string `form:"account_name"`
	Offset      uint32 `form:"offset"`
	Limit       uint32 `form:"limit"`
}

type RespGetTxsByAccountName struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"txs"`
}

type ReqGetTxsByPubKey struct {
	AccountPk string `form:"account_pk"`
	Offset    uint32 `form:"offset"`
	Limit     uint32 `form:"limit"`
}

type RespGetTxsByPubKey struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"txs"`
}

type ReqGetTxByHash struct {
	TxHash string `form:"tx_hash"`
}

type RespGetTxByHash struct {
	Tx          Tx    `json:"result"`
	CommittedAt int64 `json:"committed_at"`
	VerifiedAt  int64 `json:"verified_at"`
	ExecutedAt  int64 `json:"executed_at"`
	AssetAId    int64 `json:"asset_a_id"`
	AssetBId    int64 `json:"asset_b_id"`
}

type ReqSendTx struct {
	TxType uint32 `form:"tx_type"`
	TxInfo string `form:"tx_info"`
}

type RespSendTx struct {
	TxId string `json:"tx_id"`
}

type ReqGetMempoolTxs struct {
	Offset uint32 `form:"offset"`
	Limit  uint32 `form:"limit"`
}

type RespGetMempoolTxs struct {
	Total      uint32 `json:"total"`
	MempoolTxs []*Tx  `json:"mempool_txs"`
}

type ReqGetmempoolTxsByAccountName struct {
	AccountName string `form:"account_name"`
}

type RespGetmempoolTxsByAccountName struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"mempool_txs"`
}

type ReqGetNextNonce struct {
	AccountIndex uint32 `form:"account_index"`
}

type RespGetNextNonce struct {
	Nonce uint64 `json:"nonce"`
}

type ReqGetMaxOfferId struct {
	AccountIndex uint32 `form:"account_index"`
}

type RespGetMaxOfferId struct {
	OfferId uint64 `json:"offer_id"`
}
