// Code generated by goctl. DO NOT EDIT.
package types

type ReqGetStatus struct {
}

type RespGetStatus struct {
	Status    int `json:"status"`
	NetworkId int `json:"network_id"`
}

type Asset struct {
	AssetId         uint16 `json:"asset_id"`
	Balance         uint32 `json:"balance"`
	BalanceDecimals uint32 `json:"balance_decimals"`
}

type ReqGetAccountStatusByPubKey struct {
	AccountPk string `form:"account_pk"`
}

type RespGetAccountStatusByPubKey struct {
	AccountStatus uint8  `json:"account_status"`
	AccountName   string `json:"account_name"`
	ExpireTime    int64  `json:"expire_time"`
}

type ReqGetAccountStatusByAccountName struct {
	AccountName string `form:"account_name"`
}

type RespGetAccountStatusByAccountName struct {
	AccountStatus uint8  `json:"account_status"`
	AccountName   string `json:"account_name"`
	ExpireTime    int64  `json:"expire_time"`
}

type ReqIsAccountNameRegistered struct {
	AccountName string `form:"account_name"`
}

type RespIsAccountNameRegistered struct {
	IsRegistered int `json:"is_registered"`
}

type ReqGetAccountInfoByPubKey struct {
	AccountPk string `form:"account_pk"`
}

type RespGetAccountInfoByPubKey struct {
	AccountIndex  uint32   `json:"account_index"`
	AccountName   string   `json:"account_name"`
	AccountPk     string   `json:"account_pk"`
	AssetsAccount []*Asset `json:"assets"`
}

type ReqGetAccountInfoByAssetIdAndPubKey struct {
	AssetId   uint16 `form:"asset_id"`
	AccountPk string `form:"account_pk"`
}

type RespGetAccountInfoByAssetIdAndPubKey struct {
	AssetId      uint16 `json:"asset_id"`
	AccountIndex uint32 `json:"account_index"`
	AccountName  string `json:"account_name"`
	AccountPk    string `json:"account_pk"`
	BalanceEnc   string `json:"balance_enc"`
}

type ReqGetAccountInfoByAccountName struct {
	AccountName string `form:"account_name"`
}

type RespGetAccountInfoByAccountName struct {
	AccountIndex  uint32   `json:"account_index"`
	AccountName   string   `json:"account_name"`
	AccountPk     string   `json:"account_pk"`
	AssetsAccount []*Asset `json:"assets"`
}

type ReqGetAccountLiquidityPairs struct {
	AccountIndex uint32 `form:"account_index"`
}

type AccountLiquidityPairs struct {
	PairIndex   uint16 `json:"pair_index"`
	AssetAId    uint16 `json:"asset_a_id"`
	AssetAName  string `json:"asset_a_name"`
	AssetBId    uint16 `json:"asset_b_id"`
	AssetBName  string `json:"asset_b_name"`
	LpAmountEnc string `json:"lp_amount_enc"`
	CreatedAt   int64  `json:"created_at"`
}

type RespGetAccountLiquidityPairs struct {
	Pairs []*AccountLiquidityPairs `json:"pairs"`
}

type ReqGetAssetsList struct {
}

type L1Asset struct {
	L1AssetId       uint16 `json:"l1_asset_id"`
	L1AssetAddr     string `json:"l1_asset_addr"`
	L1AssetDecimals uint8  `json:"l1_asset_decimals"`
	L1AssetSymbol   string `json:"l1_asset_symbol"`
}

type L2Asset struct {
	L2AssetId       uint16 `json:"l2_asset_id"`
	L2AssetName     string `json:"l2_asset_name"`
	L2AssetDecimals uint8  `json:"l2_asset_decimals"`
	L2AssetSymbol   string `json:"l2_asset_symbol"`
}

type RespGetAssetsList struct {
	L1Assets []*L1Asset `json:"l1_assets"`
	L2Assets []*L2Asset `json:"l2_assets"`
}

type ReqGetCurrencyPriceBySymbol struct {
	Symbol string `form:"symbol"`
}

type RespGetCurrencyPriceBySymbol struct {
	AssetId int     `json:"assetId"`
	Price   float64 `json:"price"`
}

type ReqGetCurrencyPrices struct {
}

type DataCurrencyPrices struct {
	Pair    string  `json:"pair"`
	AssetId int     `json:"assetId"`
	Price   float64 `json:"price"`
}

type RespGetCurrencyPrices struct {
	Data []*DataCurrencyPrices `json:"data"`
}

type ReqGetGasFee struct {
	AssetId uint16 `form:"asset_id"`
}

type RespGetGasFee struct {
	GasFee float64 `json:"gas_fee"`
}

type ReqGetWithdrawGasFee struct {
	AssetId         uint16 `form:"asset_id"`
	WithdrawAssetId uint16 `form:"withdraw_asset_id"`
	WithdrawAmount  uint64 `form:"withdraw_amount"`
}

type RespGetWithdrawGasFee struct {
	WithdrawGasFee float64 `json:"withdraw_gas_fee"`
}

type ReqGetL1AmountByAssetid struct {
	AssetId uint16 `form:"asset_id"`
}

type RespGetL1AmountByAssetid struct {
	TotalAmount int64 `json:"total_amount"`
}

type ReqGetL1AmountList struct {
}

type RespGetL1AmountList struct {
	AssetId     int   `json:"asset_id"`
	TotalAmount int64 `json:"total_amount"`
}

type ReqGetSwapAmount struct {
	PairIndex   uint16 `form:"pair_index"`
	AssetId     uint16 `form:"asset_id"`
	AssetAmount uint64 `form:"asset_amount"`
	IsFrom      bool   `form:"is_from"`
}

type RespGetSwapAmount struct {
	PairIndex      uint16 `json:"pair_index"`
	ResAssetAmount uint64 `json:"res_asset_amount"`
	ResAssetId     uint16 `json:"res_asset_id"`
}

type ReqGetAvailablePairs struct {
}

type Pair struct {
	PairIndex    uint16 `json:"pair_index"`
	AssetAId     uint16 `json:"asset_a_id"`
	AssetAName   string `json:"asset_a_name"`
	AssetBId     uint16 `json:"asset_b_id"`
	AssetBName   string `json:"asset_b_name"`
	FeeRate      int64  `json:"fee_Rate"`
	TreasuryRate int64  `json:"treasury_rate"`
}

type RespGetAvailablePairs struct {
	Pairs []*Pair `json:"result"`
}

type ReqGetLPValue struct {
	PairIndex uint16 `form:"pair_index"`
	LpAmount  uint64 `form:"lp_amount"`
}

type RespGetLPValue struct {
	AssetAId     uint16 `json:"asset_a_id"`
	AssetAName   string `json:"asset_a_name"`
	AssetAAmount uint64 `json:"asset_a_amount"`
	AssetBid     uint16 `json:"asset_b_id"`
	AssetBName   string `json:"asset_b_name"`
	AssetBAmount uint64 `json:"asset_b_amount"`
}

type ReqGetPairInfo struct {
	PairIndex uint16 `form:"pair_index"`
}

type RespGetPairInfo struct {
	AssetRatio    float64 `json:"asset_ratio"`
	AssetAId      uint16  `json:"asset_a_id"`
	AssetAAmount  uint64  `json:"asset_a_amount"`
	AssetBId      uint16  `json:"asset_b_id"`
	AssetBAmount  uint64  `json:"asset_b_amount"`
	TotalLpAmount uint64  `json:"total_lp_amount"`
}

type TxDetail struct {
	AssetId      int    `json:"assetId"`
	AssetType    int    `json:"assetType"`
	AccountIndex int32  `json:"accountIndex"`
	AccountName  string `json:"accountName"`
	AccountDelta string `json:"accountDelta"`
}

type Tx struct {
	TxHash        string      `json:"tx_hash"`
	TxType        uint8       `json:"tx_type,range=[1:64]"`
	GasFee        int64       `json:"gas_fee"`
	GasFeeAssetId uint16      `json:"gas_fee_asset_id"`
	TxStatus      int         `json:"tx_status,options=0|1|2"`
	BlockHeight   int         `json:"block_height"`
	BlockStatus   int         `json:"block_status"`
	BlockId       int         `json:"block_id"`
	AssetAId      int         `json:"asset_a_id"`
	AssetBId      int         `json:"asset_b_id"`
	TxAmount      int         `json:"tx_amount"`
	TxDetails     []*TxDetail `json:"tx_detail"`
	NativeAddress string      `json:"native_address"`
	CreatedAt     int64       `json:"created_at"`
	Memo          string      `json:"memo"`
}

type TxAccount struct {
	AccountIndex   int    `json:"account_index"`
	AccountName    string `json:"account_name"`
	AccountBalance string `json:"account_balance"`
	AccountDelta   string `json:"account_delta"`
}

type ReqGetTxsByAccountIndexAndTxType struct {
	Pk     string `form:"account_index"`
	TxType uint8  `form:"tx_type"`
	Offset uint16 `form:"offset"`
	Limit  uint16 `form:"limit"`
}

type RespGetTxsByAccountIndexAndTxType struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"txs"`
}

type ReqGetTxsByAccountName struct {
	AccountName string `form:"account_name"`
	Offset      uint16 `form:"offset"`
	Limit       uint16 `form:"limit"`
}

type RespGetTxsByAccountName struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"txs"`
}

type ReqGetTxsByPubKey struct {
	Pk     string `form:"pk"`
	Offset uint16 `form:"offset"`
	Limit  uint16 `form:"limit"`
}

type RespGetTxsByPubKey struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"txs"`
}

type ReqGetTxByHash struct {
	TxHash string `form:"tx_hash"`
}

type RespGetTxByHash struct {
	Tx          Tx    `json:"result"`
	CommittedAt int64 `json:"committed_at"`
	VerifiedAt  int64 `json:"verified_at"`
	ExecutedAt  int64 `json:"executed_at"`
}

type ReqSendTx struct {
	TxType uint8  `form:"tx_type"`
	TxInfo string `form:"tx_info"`
}

type RespSendTx struct {
	TxId string `json:"tx_id"`
}

type ReqGetMempoolTxs struct {
	Offset uint16 `form:"offset"`
	Limit  uint16 `form:"limit"`
}

type RespGetMempoolTxs struct {
	Total      uint32 `json:"total"`
	MempoolTxs []*Tx  `json:"mempool_txs"`
}
