// check option don't need to return error, because error is determined by business logic
// sometimes, the true case represents error. sometimes the false case indicates error, ever if that two case is generated by same checkFunc
package utils

import (
	"strings"
)

const (
	maxAccountNameLength          = 30
	maxAccountNameLengthOmitSpace = 20

	minAssetId = 0
	maxAssetId = 1 << 32
)

func CheckAccountName(accountName string) bool {
	return len(accountName) > maxAccountNameLength
}

func CheckFormatAccountName(accountName string) bool {
	return len(accountName) > maxAccountNameLengthOmitSpace
}

// func CheckeAssetId(assetId uint16) bool {
// 	return assetId > maxAssetId
// }

func FormatSting(name string) string {
	name = strings.ToLower(name)
	name = strings.Replace(name, "\n", "", -1)
	return name
}
