apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: default
spec:
  ports:
  - port: 8888
  selector:
    app: app
---
apiVersion: v1
kind: Service
metadata:
  name: globalrpc-svc
  namespace: default
spec:
  ports:
  - port: 8080
  selector:
    app: globalrpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: find-endpoints
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/app:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 8888
        name: app
        ports:
          - name: metrics
            containerPort: 9091
          - name: app
            containerPort: 8888
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8888
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      initContainers:
      - command:
        - sh
        - -c
        - until nslookup globalrpc-svc; do echo waiting for globalrpc; sleep 2; done;
        image: busybox
        name: init-globalrpc
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: committer
  name: committer
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: committer
  template:
    metadata:
      labels:
        app: committer
    spec:
      serviceAccountName: find-endpoints
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/committer:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: committer
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: globalrpc
  name: globalrpc
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: globalrpc
  template:
    metadata:
      labels:
        app: globalrpc
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/globalrpc:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 20
          tcpSocket:
            port: 8080
        name: globalrpc
        ports:
        - name: metrics
          containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monitor
  name: monitor
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/monitor:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: monitor
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: witnessgenerator
  name: witnessgenerator
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: witnessgenerator
  template:
    metadata:
      labels:
        app: witnessgenerator
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/witnessgenerator:$TAG_NAME
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 5
          name: witnessgenerator
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
      volumes:
        - hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
          name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prover
  name: prover
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: prover
  template:
    metadata:
      labels:
        app: prover
    spec:
      serviceAccountName: find-endpoints
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/prover:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: prover
        resources:
          limits:
            cpu: 2000m
            memory: 8192Mi
          requests:
            cpu: 500m
            memory: 2048Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sender
  name: sender
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/zecrey-330903/zecrey-webhook/sender:$TAG_NAME
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 5
        name: sender
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
        name: timezone
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: app-hpa-c
  name: app-hpa-c
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: app-hpa-m
  name: app-hpa-m
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: memory
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: globalrpc-hpa-c
  name: globalrpc-hpa-c
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: globalrpc
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: globalrpc-hpa-m
  name: globalrpc-hpa-m
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: memory
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: globalrpc
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: prover-hpa-c
  name: prover-hpa-c
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prover
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: prover-hpa-m
  name: prover-hpa-m
  namespace: default
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: memory
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prover
