// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proverHub.proto

package proverHubProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// getUnprovedBlock
type ReqGetUnprovedBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode int64 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *ReqGetUnprovedBlock) Reset() {
	*x = ReqGetUnprovedBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proverHub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetUnprovedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetUnprovedBlock) ProtoMessage() {}

func (x *ReqGetUnprovedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proverHub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetUnprovedBlock.ProtoReflect.Descriptor instead.
func (*ReqGetUnprovedBlock) Descriptor() ([]byte, []int) {
	return file_proverHub_proto_rawDescGZIP(), []int{0}
}

func (x *ReqGetUnprovedBlock) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type ResultGetUnprovedBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockInfo string `protobuf:"bytes,1,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
}

func (x *ResultGetUnprovedBlock) Reset() {
	*x = ResultGetUnprovedBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proverHub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultGetUnprovedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultGetUnprovedBlock) ProtoMessage() {}

func (x *ResultGetUnprovedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proverHub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultGetUnprovedBlock.ProtoReflect.Descriptor instead.
func (*ResultGetUnprovedBlock) Descriptor() ([]byte, []int) {
	return file_proverHub_proto_rawDescGZIP(), []int{1}
}

func (x *ResultGetUnprovedBlock) GetBlockInfo() string {
	if x != nil {
		return x.BlockInfo
	}
	return ""
}

type RespGetUnprovedBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64                   `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Msg    string                  `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Err    string                  `protobuf:"bytes,3,opt,name=Err,proto3" json:"Err,omitempty"`
	Result *ResultGetUnprovedBlock `protobuf:"bytes,4,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *RespGetUnprovedBlock) Reset() {
	*x = RespGetUnprovedBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proverHub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespGetUnprovedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetUnprovedBlock) ProtoMessage() {}

func (x *RespGetUnprovedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proverHub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetUnprovedBlock.ProtoReflect.Descriptor instead.
func (*RespGetUnprovedBlock) Descriptor() ([]byte, []int) {
	return file_proverHub_proto_rawDescGZIP(), []int{2}
}

func (x *RespGetUnprovedBlock) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RespGetUnprovedBlock) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RespGetUnprovedBlock) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *RespGetUnprovedBlock) GetResult() *ResultGetUnprovedBlock {
	if x != nil {
		return x.Result
	}
	return nil
}

// submitUnprovedBlock
type ReqSubmitProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Proof     string `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	BlockInfo string `protobuf:"bytes,2,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
}

func (x *ReqSubmitProof) Reset() {
	*x = ReqSubmitProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proverHub_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSubmitProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSubmitProof) ProtoMessage() {}

func (x *ReqSubmitProof) ProtoReflect() protoreflect.Message {
	mi := &file_proverHub_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSubmitProof.ProtoReflect.Descriptor instead.
func (*ReqSubmitProof) Descriptor() ([]byte, []int) {
	return file_proverHub_proto_rawDescGZIP(), []int{3}
}

func (x *ReqSubmitProof) GetProof() string {
	if x != nil {
		return x.Proof
	}
	return ""
}

func (x *ReqSubmitProof) GetBlockInfo() string {
	if x != nil {
		return x.BlockInfo
	}
	return ""
}

type ResultSubmitProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResultSubmitProof) Reset() {
	*x = ResultSubmitProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proverHub_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultSubmitProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultSubmitProof) ProtoMessage() {}

func (x *ResultSubmitProof) ProtoReflect() protoreflect.Message {
	mi := &file_proverHub_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultSubmitProof.ProtoReflect.Descriptor instead.
func (*ResultSubmitProof) Descriptor() ([]byte, []int) {
	return file_proverHub_proto_rawDescGZIP(), []int{4}
}

type RespSubmitProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64              `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Msg    string             `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Err    string             `protobuf:"bytes,3,opt,name=Err,proto3" json:"Err,omitempty"`
	Result *ResultSubmitProof `protobuf:"bytes,4,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *RespSubmitProof) Reset() {
	*x = RespSubmitProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proverHub_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespSubmitProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespSubmitProof) ProtoMessage() {}

func (x *RespSubmitProof) ProtoReflect() protoreflect.Message {
	mi := &file_proverHub_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespSubmitProof.ProtoReflect.Descriptor instead.
func (*RespSubmitProof) Descriptor() ([]byte, []int) {
	return file_proverHub_proto_rawDescGZIP(), []int{5}
}

func (x *RespSubmitProof) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RespSubmitProof) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RespSubmitProof) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *RespSubmitProof) GetResult() *ResultSubmitProof {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proverHub_proto protoreflect.FileDescriptor

var file_proverHub_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x48, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x48, 0x75, 0x62, 0x22, 0x29, 0x0a, 0x13,
	0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x36, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x8d, 0x01, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x45, 0x72, 0x72, 0x12, 0x39, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x48, 0x75, 0x62,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x70, 0x72, 0x6f, 0x76,
	0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x44, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f,
	0x66, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0x83, 0x01, 0x0a, 0x0f, 0x52,
	0x65, 0x73, 0x70, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x72, 0x72, 0x12, 0x34, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x72, 0x48, 0x75, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0xa9, 0x01, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x48, 0x75, 0x62, 0x52, 0x50,
	0x43, 0x12, 0x53, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x55, 0x6e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x48, 0x75,
	0x62, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x48, 0x75,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x44, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x48, 0x75,
	0x62, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x48, 0x75, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x42, 0x12, 0x5a, 0x10,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x72, 0x48, 0x75, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proverHub_proto_rawDescOnce sync.Once
	file_proverHub_proto_rawDescData = file_proverHub_proto_rawDesc
)

func file_proverHub_proto_rawDescGZIP() []byte {
	file_proverHub_proto_rawDescOnce.Do(func() {
		file_proverHub_proto_rawDescData = protoimpl.X.CompressGZIP(file_proverHub_proto_rawDescData)
	})
	return file_proverHub_proto_rawDescData
}

var file_proverHub_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proverHub_proto_goTypes = []interface{}{
	(*ReqGetUnprovedBlock)(nil),    // 0: proverHub.ReqGetUnprovedBlock
	(*ResultGetUnprovedBlock)(nil), // 1: proverHub.ResultGetUnprovedBlock
	(*RespGetUnprovedBlock)(nil),   // 2: proverHub.RespGetUnprovedBlock
	(*ReqSubmitProof)(nil),         // 3: proverHub.ReqSubmitProof
	(*ResultSubmitProof)(nil),      // 4: proverHub.ResultSubmitProof
	(*RespSubmitProof)(nil),        // 5: proverHub.RespSubmitProof
}
var file_proverHub_proto_depIdxs = []int32{
	1, // 0: proverHub.RespGetUnprovedBlock.Result:type_name -> proverHub.ResultGetUnprovedBlock
	4, // 1: proverHub.RespSubmitProof.Result:type_name -> proverHub.ResultSubmitProof
	0, // 2: proverHub.proverHubRPC.getUnprovedBlock:input_type -> proverHub.ReqGetUnprovedBlock
	3, // 3: proverHub.proverHubRPC.submitProof:input_type -> proverHub.ReqSubmitProof
	2, // 4: proverHub.proverHubRPC.getUnprovedBlock:output_type -> proverHub.RespGetUnprovedBlock
	5, // 5: proverHub.proverHubRPC.submitProof:output_type -> proverHub.RespSubmitProof
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proverHub_proto_init() }
func file_proverHub_proto_init() {
	if File_proverHub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proverHub_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetUnprovedBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proverHub_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultGetUnprovedBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proverHub_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespGetUnprovedBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proverHub_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSubmitProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proverHub_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultSubmitProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proverHub_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespSubmitProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proverHub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proverHub_proto_goTypes,
		DependencyIndexes: file_proverHub_proto_depIdxs,
		MessageInfos:      file_proverHub_proto_msgTypes,
	}.Build()
	File_proverHub_proto = out.File
	file_proverHub_proto_rawDesc = nil
	file_proverHub_proto_goTypes = nil
	file_proverHub_proto_depIdxs = nil
}
