// check option don't need to return error, because error is determined by business logic
// sometimes, the true case represents error. sometimes the false case indicates error, ever if that two case is generated by same checkFunc
package checker

import (
	"math"
	"strings"
)

const (
	maxAccountNameLength          = 30
	maxAccountNameLengthOmitSpace = 20

	minAssetId = 0
	maxAssetId = math.MaxUint32

	minAccountIndex = 0
	maxAccountIndex = math.MaxUint32
)

func CheckAccountName(accountName string) bool {
	return len(accountName) > maxAccountNameLength
}

func CheckFormatAccountName(accountName string) bool {
	return len(accountName) > maxAccountNameLengthOmitSpace
}

func CheckAssetId(assetId uint32) bool {
	return assetId > maxAssetId
}

func CheckPairIndex(pairIndex uint32) bool {
	return pairIndex > maxAccountIndex
}

func CheckOffset(offset, total uint32) bool {
	return offset < total
}

// Format AccountName and
func FormatSting(name string) string {
	name = strings.ToLower(name)
	name = strings.Replace(name, "\n", "", -1)
	return name
}
