// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
	"paths": {
    "/": {
      "get": {
        "summary": "Get status of zkbnb",
        "operationId": "GetStatus",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          }
        },
        "requestBody": {},
        "tags": [
          "root"
        ]
      }
    },
    "/api/v1/account": {
      "get": {
        "summary": "Get account by account's name, index or pk",
        "operationId": "GetAccount",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Account"
            }
          }
        },
        "parameters": [
          {
            "name": "by",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "value",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "requestBody": {},
        "tags": [
          "account"
        ]
      }
    },
    "/api/v1/accountNfts": {
      "get": {
        "summary": "Get nfts of a specific account",
        "operationId": "GetAccountNfts",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Nfts"
            }
          }
        },
        "parameters": [
          {
            "name": "by",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "value",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "offset",
            "in": "query",
            "required": true,
            "type": "invalid",
            "format": "UNKNOWN"
          },
          {
            "name": "limit",
            "in": "query",
            "required": true,
            "type": "invalid",
            "format": "UNKNOWN"
          }
        ],
        "requestBody": {},
        "tags": [
          "nft"
        ]
      }
    },
    "/api/v1/accountPendingTxs": {
      "get": {
        "summary": "Get pending transactions of a specific account",
        "operationId": "GetAccountPendingTxs",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Txs"
            }
          }
        },
        "parameters": [
          {
            "name": "by",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "value",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "types",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int64"
          }
        ],
        "requestBody": {},
        "tags": [
          "transaction"
        ]
      }
    },
    "/api/v1/accountTxs": {
      "get": {
        "summary": "Get transactions of a specific account",
        "operationId": "GetAccountTxs",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Txs"
            }
          }
        },
        "parameters": [
          {
            "name": "by",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "value",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "types",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int64"
          },
          {
            "name": "offset",
            "in": "query",
            "required": true,
            "type": "invalid",
            "format": "UNKNOWN"
          },
          {
            "name": "limit",
            "in": "query",
            "required": true,
            "type": "invalid",
            "format": "UNKNOWN"
          }
        ],
        "requestBody": {},
        "tags": [
          "transaction"
        ]
      }
    },
    "/api/v1/accounts": {
      "get": {
        "summary": "Get accounts",
        "operationId": "GetAccounts",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Accounts"
            }
          }
        },
        "parameters": [
          {
            "name": "offset",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "limit",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "requestBody": {},
        "tags": [
          "account"
        ]
      }
    },
    "/api/v1/asset": {
      "get": {
        "summary": "Get asset",
        "operationId": "GetAsset",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Asset"
            }
          }
        },
        "parameters": [
          {
            "name": "by",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "value",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "requestBody": {},
        "tags": [
          "asset"
        ]
      }
    },
    "/api/v1/assets": {
      "get": {
        "summary": "Get assets",
        "operationId": "GetAssets",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Assets"
            }
          }
        },
        "parameters": [
          {
            "name": "offset",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "limit",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "requestBody": {},
        "tags": [
          "asset"
        ]
      }
    },
    "/api/v1/block": {
      "get": {
        "summary": "Get block by its height or commitment",
        "operationId": "GetBlock",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Block"
            }
          }
        },
        "parameters": [
          {
            "name": "by",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "value",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "requestBody": {},
        "tags": [
          "block"
        ]
      }
    },
    "/api/v1/blockTxs": {
      "get": {
        "summary": "Get transactions in a block",
        "operationId": "GetBlockTxs",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Txs"
            }
          }
        },
        "parameters": [
          {
            "name": "by",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "value",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "requestBody": {},
        "tags": [
          "transaction"
        ]
      }
    },
    "/api/v1/blocks": {
      "get": {
        "summary": "Get blocks",
        "operationId": "GetBlocks",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Blocks"
            }
          }
        },
        "parameters": [
          {
            "name": "offset",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "limit",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "requestBody": {},
        "tags": [
          "block"
        ]
      }
    },
    "/api/v1/currentHeight": {
      "get": {
        "operationId": "GetCurrentHeight",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/CurrentHeight"
            }
          }
        },
        "requestBody": {},
        "tags": [
          "block"
        ]
      }
    },
    "/api/v1/executedTxs": {
      "get": {
        "summary": "Get executed transactions which previously added to tx pool",
        "operationId": "GetExecutedTxs",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Txs"
            }
          }
        },
        "parameters": [
          {
            "name": "offset",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "limit",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "from_hash",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "requestBody": {},
        "tags": [
          "transaction"
        ]
      }
    },
    "/api/v1/gasAccount": {
      "get": {
        "summary": "Get gas account, who will charge gas fees for transactions",
        "operationId": "GetGasAccount",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/GasAccount"
            }
          }
        },
        "requestBody": {},
        "tags": [
          "info"
        ]
      }
    },
    "/api/v1/gasFee": {
      "get": {
        "summary": "Get gas fee amount for using a specific asset as gas asset",
        "operationId": "GetGasFee",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/GasFee"
            }
          }
        },
        "parameters": [
          {
            "name": "asset_id",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "tx_type",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "requestBody": {},
        "tags": [
          "info"
        ]
      }
    },
    "/api/v1/gasFeeAssets": {
      "get": {
        "summary": "Get supported gas fee assets",
        "operationId": "GetGasFeeAssets",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/GasFeeAssets"
            }
          }
        },
        "requestBody": {},
        "tags": [
          "info"
        ]
      }
    },
    "/api/v1/layer2BasicInfo": {
      "get": {
        "summary": "Get zkbnb general info, including contract address, and count of transactions and active users",
        "operationId": "GetLayer2BasicInfo",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Layer2BasicInfo"
            }
          }
        },
        "requestBody": {},
        "tags": [
          "info"
        ]
      }
    },
    "/api/v1/maxOfferId": {
      "get": {
        "summary": "Get max nft offer id for a specific account",
        "operationId": "GetMaxOfferId",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/MaxOfferId"
            }
          }
        },
        "parameters": [
          {
            "name": "account_index",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "requestBody": {},
        "tags": [
          "nft"
        ]
      }
    },
    "/api/v1/nextNonce": {
      "get": {
        "summary": "Get next nonce",
        "operationId": "GetNextNonce",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/NextNonce"
            }
          }
        },
        "parameters": [
          {
            "name": "account_index",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "requestBody": {},
        "tags": [
          "transaction"
        ]
      }
    },
    "/api/v1/pendingTxs": {
      "get": {
        "summary": "Get pending transactions",
        "operationId": "GetPendingTxs",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Txs"
            }
          }
        },
        "parameters": [
          {
            "name": "offset",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "limit",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "requestBody": {},
        "tags": [
          "transaction"
        ]
      }
    },
    "/api/v1/search": {
      "get": {
        "summary": "Search with a specific keyword",
        "operationId": "Search",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Search"
            }
          }
        },
        "parameters": [
          {
            "name": "keyword",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "requestBody": {},
        "tags": [
          "info"
        ]
      }
    },
    "/api/v1/sendTx": {
      "post": {
        "summary": "Send raw transaction",
        "operationId": "SendTx",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/TxHash"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ReqSendTx"
            }
          }
        ],
        "requestBody": {},
        "tags": [
          "transaction"
        ]
      }
    },
    "/api/v1/tx": {
      "get": {
        "summary": "Get transaction by hash",
        "operationId": "GetTx",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/EnrichedTx"
            }
          }
        },
        "parameters": [
          {
            "name": "hash",
            "in": "query",
            "required": true,
            "type": "string"
          }
        ],
        "requestBody": {},
        "tags": [
          "transaction"
        ]
      }
    },
    "/api/v1/txs": {
      "get": {
        "summary": "Get transactions which are already packed into blocks",
        "operationId": "GetTxs",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/Txs"
            }
          }
        },
        "parameters": [
          {
            "name": "offset",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "limit",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32"
          }
        ],
        "requestBody": {},
        "tags": [
          "transaction"
        ]
      }
    }
  },
  "definitions": {
    "Account": {
      "type": "object",
      "properties": {
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "index": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        },
        "pk": {
          "type": "string"
        },
        "nonce": {
          "type": "integer",
          "format": "int64"
        },
        "assets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/AccountAsset"
          }
        },
        "total_asset_value": {
          "type": "string"
        }
      },
      "title": "Account",
      "required": [
        "status",
        "index",
        "name",
        "pk",
        "nonce",
        "assets",
        "total_asset_value"
      ]
    },
    "AccountAsset": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "balance": {
          "type": "string"
        },
        "price": {
          "type": "string"
        }
      },
      "title": "AccountAsset",
      "required": [
        "id",
        "name",
        "balance",
        "price"
      ]
    },
    "Accounts": {
      "type": "object",
      "properties": {
        "total": {
          "type": "integer",
          "format": "int32"
        },
        "accounts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SimpleAccount"
          }
        }
      },
      "title": "Accounts",
      "required": [
        "total",
        "accounts"
      ]
    },
    "Asset": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "decimals": {
          "type": "integer",
          "format": "int32"
        },
        "symbol": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "price": {
          "type": "string"
        },
        "is_gas_asset": {
          "type": "integer",
          "format": "int32"
        },
        "icon": {
          "type": "string"
        }
      },
      "title": "Asset",
      "required": [
        "id",
        "name",
        "decimals",
        "symbol",
        "address",
        "price",
        "is_gas_asset",
        "icon"
      ]
    },
    "Assets": {
      "type": "object",
      "properties": {
        "total": {
          "type": "integer",
          "format": "int32"
        },
        "assets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Asset"
          }
        }
      },
      "title": "Assets",
      "required": [
        "total",
        "assets"
      ]
    },
    "Block": {
      "type": "object",
      "properties": {
        "commitment": {
          "type": "string"
        },
        "height": {
          "type": "integer",
          "format": "int64"
        },
        "state_root": {
          "type": "string"
        },
        "priority_operations": {
          "type": "integer",
          "format": "int64"
        },
        "pending_on_chain_operations_hash": {
          "type": "string"
        },
        "pending_on_chain_operations_pub_data": {
          "type": "string"
        },
        "committed_tx_hash": {
          "type": "string"
        },
        "committed_at": {
          "type": "integer",
          "format": "int64"
        },
        "verified_tx_hash": {
          "type": "string"
        },
        "verified_at": {
          "type": "integer",
          "format": "int64"
        },
        "txs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Tx"
          }
        },
        "status": {
          "type": "integer",
          "format": "int64"
        },
        "size": {
          "$ref": "#/definitions/uint16"
        }
      },
      "title": "Block",
      "required": [
        "commitment",
        "height",
        "state_root",
        "priority_operations",
        "pending_on_chain_operations_hash",
        "pending_on_chain_operations_pub_data",
        "committed_tx_hash",
        "committed_at",
        "verified_tx_hash",
        "verified_at",
        "txs",
        "status",
        "size"
      ]
    },
    "Blocks": {
      "type": "object",
      "properties": {
        "total": {
          "type": "integer",
          "format": "int32"
        },
        "blocks": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Block"
          }
        }
      },
      "title": "Blocks",
      "required": [
        "total",
        "blocks"
      ]
    },
    "ContractAddress": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "address": {
          "type": "string"
        }
      },
      "title": "ContractAddress",
      "required": [
        "name",
        "address"
      ]
    },
    "CurrentHeight": {
      "type": "object",
      "properties": {
        "height": {
          "type": "integer",
          "format": "int64"
        }
      },
      "title": "CurrentHeight",
      "required": [
        "height"
      ]
    },
    "EnrichedTx": {
      "type": "object",
      "properties": {
        "": {
          "$ref": "#/definitions/Tx"
        },
        "committed_at": {
          "type": "integer",
          "format": "int64"
        },
        "verified_at": {
          "type": "integer",
          "format": "int64"
        },
        "executed_at": {
          "type": "integer",
          "format": "int64"
        }
      },
      "title": "EnrichedTx",
      "required": [
        "committed_at",
        "verified_at",
        "executed_at"
      ]
    },
    "GasAccount": {
      "type": "object",
      "properties": {
        "status": {
          "type": "integer",
          "format": "int64"
        },
        "index": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        }
      },
      "title": "GasAccount",
      "required": [
        "status",
        "index",
        "name"
      ]
    },
    "GasFee": {
      "type": "object",
      "properties": {
        "gas_fee": {
          "type": "string"
        }
      },
      "title": "GasFee",
      "required": [
        "gas_fee"
      ]
    },
    "GasFeeAssets": {
      "type": "object",
      "properties": {
        "assets": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Asset"
          }
        }
      },
      "title": "GasFeeAssets",
      "required": [
        "assets"
      ]
    },
    "Layer2BasicInfo": {
      "type": "object",
      "properties": {
        "block_committed": {
          "type": "integer",
          "format": "int64"
        },
        "block_verified": {
          "type": "integer",
          "format": "int64"
        },
        "total_transaction_count": {
          "type": "integer",
          "format": "int64"
        },
        "yesterday_transaction_count": {
          "type": "integer",
          "format": "int64"
        },
        "today_transaction_count": {
          "type": "integer",
          "format": "int64"
        },
        "yesterday_active_user_count": {
          "type": "integer",
          "format": "int64"
        },
        "today_active_user_count": {
          "type": "integer",
          "format": "int64"
        },
        "contract_addresses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ContractAddress"
          }
        }
      },
      "title": "Layer2BasicInfo",
      "required": [
        "block_committed",
        "block_verified",
        "total_transaction_count",
        "yesterday_transaction_count",
        "today_transaction_count",
        "yesterday_active_user_count",
        "today_active_user_count",
        "contract_addresses"
      ]
    },
    "MaxOfferId": {
      "type": "object",
      "properties": {
        "offer_id": {
          "type": "integer",
          "format": "int64"
        }
      },
      "title": "MaxOfferId",
      "required": [
        "offer_id"
      ]
    },
    "NextNonce": {
      "type": "object",
      "properties": {
        "nonce": {
          "type": "integer",
          "format": "int64"
        }
      },
      "title": "NextNonce",
      "required": [
        "nonce"
      ]
    },
    "Nft": {
      "type": "object",
      "properties": {
        "index": {
          "type": "integer",
          "format": "int64"
        },
        "creator_account_index": {
          "type": "integer",
          "format": "int64"
        },
        "creator_account_name": {
          "type": "string"
        },
        "owner_account_index": {
          "type": "integer",
          "format": "int64"
        },
        "owner_account_name": {
          "type": "string"
        },
        "content_hash": {
          "type": "string"
        },
        "l1_address": {
          "type": "string"
        },
        "l1_token_id": {
          "type": "string"
        },
        "creator_treasury_rate": {
          "type": "integer",
          "format": "int64"
        },
        "collection_id": {
          "type": "integer",
          "format": "int64"
        }
      },
      "title": "Nft",
      "required": [
        "index",
        "creator_account_index",
        "creator_account_name",
        "owner_account_index",
        "owner_account_name",
        "content_hash",
        "l1_address",
        "l1_token_id",
        "creator_treasury_rate",
        "collection_id"
      ]
    },
    "Nfts": {
      "type": "object",
      "properties": {
        "total": {
          "type": "integer",
          "format": "int64"
        },
        "nfts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Nft"
          }
        }
      },
      "title": "Nfts",
      "required": [
        "total",
        "nfts"
      ]
    },
    "ReqGetAccount": {
      "type": "object",
      "properties": {
        "by": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "title": "ReqGetAccount",
      "required": [
        "by",
        "value"
      ]
    },
    "ReqGetAccountNfts": {
      "type": "object",
      "properties": {
        "by": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "offset": {
          "$ref": "#/definitions/uint16"
        },
        "limit": {
          "$ref": "#/definitions/uint16"
        }
      },
      "title": "ReqGetAccountNfts",
      "required": [
        "by",
        "value",
        "offset",
        "limit"
      ]
    },
    "ReqGetAccountPendingTxs": {
      "type": "object",
      "properties": {
        "by": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "types": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int64"
          }
        }
      },
      "title": "ReqGetAccountPendingTxs",
      "required": [
        "by",
        "value"
      ]
    },
    "ReqGetAccountTxs": {
      "type": "object",
      "properties": {
        "by": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "types": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int64"
          }
        },
        "offset": {
          "$ref": "#/definitions/uint16"
        },
        "limit": {
          "$ref": "#/definitions/uint16"
        }
      },
      "title": "ReqGetAccountTxs",
      "required": [
        "by",
        "value",
        "offset",
        "limit"
      ]
    },
    "ReqGetAsset": {
      "type": "object",
      "properties": {
        "by": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "title": "ReqGetAsset",
      "required": [
        "by",
        "value"
      ]
    },
    "ReqGetBlock": {
      "type": "object",
      "properties": {
        "by": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "title": "ReqGetBlock",
      "required": [
        "by",
        "value"
      ]
    },
    "ReqGetBlockTxs": {
      "type": "object",
      "properties": {
        "by": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "title": "ReqGetBlockTxs",
      "required": [
        "by",
        "value"
      ]
    },
    "ReqGetGasFee": {
      "type": "object",
      "properties": {
        "asset_id": {
          "type": "integer",
          "format": "int32"
        },
        "tx_type": {
          "type": "integer",
          "format": "int32"
        }
      },
      "title": "ReqGetGasFee",
      "required": [
        "asset_id",
        "tx_type"
      ]
    },
    "ReqGetMaxOfferId": {
      "type": "object",
      "properties": {
        "account_index": {
          "type": "integer",
          "format": "int32"
        }
      },
      "title": "ReqGetMaxOfferId",
      "required": [
        "account_index"
      ]
    },
    "ReqGetNextNonce": {
      "type": "object",
      "properties": {
        "account_index": {
          "type": "integer",
          "format": "int32"
        }
      },
      "title": "ReqGetNextNonce",
      "required": [
        "account_index"
      ]
    },
    "ReqGetRange": {
      "type": "object",
      "properties": {
        "offset": {
          "type": "integer",
          "format": "int32"
        },
        "limit": {
          "type": "integer",
          "format": "int32"
        }
      },
      "title": "ReqGetRange",
      "required": [
        "offset",
        "limit"
      ]
    },
    "ReqGetRangeWithFromHash": {
      "type": "object",
      "properties": {
        "offset": {
          "type": "integer",
          "format": "int32"
        },
        "limit": {
          "type": "integer",
          "format": "int32"
        },
        "from_hash": {
          "type": "string"
        }
      },
      "title": "ReqGetRangeWithFromHash",
      "required": [
        "offset",
        "limit"
      ]
    },
    "ReqGetTx": {
      "type": "object",
      "properties": {
        "hash": {
          "type": "string"
        }
      },
      "title": "ReqGetTx",
      "required": [
        "hash"
      ]
    },
    "ReqSearch": {
      "type": "object",
      "properties": {
        "keyword": {
          "type": "string"
        }
      },
      "title": "ReqSearch",
      "required": [
        "keyword"
      ]
    },
    "ReqSendTx": {
      "type": "object",
      "properties": {
        "tx_type": {
          "type": "integer",
          "format": "int32"
        },
        "tx_info": {
          "type": "string"
        }
      },
      "title": "ReqSendTx",
      "required": [
        "tx_type",
        "tx_info"
      ]
    },
    "Search": {
      "type": "object",
      "properties": {
        "data_type": {
          "type": "integer",
          "format": "int32"
        }
      },
      "title": "Search",
      "required": [
        "data_type"
      ]
    },
    "SimpleAccount": {
      "type": "object",
      "properties": {
        "index": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        },
        "pk": {
          "type": "string"
        }
      },
      "title": "SimpleAccount",
      "required": [
        "index",
        "name",
        "pk"
      ]
    },
    "Status": {
      "type": "object",
      "properties": {
        "status": {
          "type": "integer",
          "format": "int32"
        },
        "network_id": {
          "type": "integer",
          "format": "int32"
        }
      },
      "title": "Status",
      "required": [
        "status",
        "network_id"
      ]
    },
    "Tx": {
      "type": "object",
      "properties": {
        "hash": {
          "type": "string"
        },
        "type": {
          "type": "integer",
          "format": "int64"
        },
        "amount": {
          "type": "string"
        },
        "info": {
          "type": "string"
        },
        "status": {
          "type": "integer",
          "format": "int64"
        },
        "index": {
          "type": "integer",
          "format": "int64"
        },
        "gas_fee_asset_id": {
          "type": "integer",
          "format": "int64"
        },
        "gas_fee": {
          "type": "string"
        },
        "nft_index": {
          "type": "integer",
          "format": "int64"
        },
        "collection_id": {
          "type": "integer",
          "format": "int64"
        },
        "asset_id": {
          "type": "integer",
          "format": "int64"
        },
        "asset_name": {
          "type": "string"
        },
        "native_address": {
          "type": "string"
        },
        "extra_info": {
          "type": "string"
        },
        "memo": {
          "type": "string"
        },
        "account_index": {
          "type": "integer",
          "format": "int64"
        },
        "account_name": {
          "type": "string"
        },
        "nonce": {
          "type": "integer",
          "format": "int64"
        },
        "expire_at": {
          "type": "integer",
          "format": "int64"
        },
        "block_height": {
          "type": "integer",
          "format": "int64"
        },
        "created_at": {
          "type": "integer",
          "format": "int64"
        },
        "state_root": {
          "type": "string"
        },
        "to_account_index": {
          "type": "integer",
          "format": "int64"
        },
        "to_account_name": {
          "type": "string"
        }
      },
      "title": "Tx",
      "required": [
        "hash",
        "type",
        "amount",
        "info",
        "status",
        "index",
        "gas_fee_asset_id",
        "gas_fee",
        "nft_index",
        "collection_id",
        "asset_id",
        "asset_name",
        "native_address",
        "extra_info",
        "memo",
        "account_index",
        "account_name",
        "nonce",
        "expire_at",
        "block_height",
        "created_at",
        "state_root",
        "to_account_index",
        "to_account_name"
      ]
    },
    "TxHash": {
      "type": "object",
      "properties": {
        "tx_hash": {
          "type": "string"
        }
      },
      "title": "TxHash",
      "required": [
        "tx_hash"
      ]
    },
    "Txs": {
      "type": "object",
      "properties": {
        "total": {
          "type": "integer",
          "format": "int32"
        },
        "txs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Tx"
          }
        }
      },
      "title": "Txs",
      "required": [
        "total",
        "txs"
      ]
    }
  },
  "securityDefinitions": {
    "apiKey": {
      "type": "apiKey",
      "description": "Enter JWT Bearer token **_only_**",
      "name": "Authorization",
      "in": "header"
    }
  }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
