// Code generated by goctl. DO NOT EDIT!
// Source: blockMonitor.proto

package blockMonitor

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BlockMonitor interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultBlockMonitor struct {
		cli zrpc.Client
	}
)

func NewBlockMonitor(cli zrpc.Client) BlockMonitor {
	return &defaultBlockMonitor{
		cli: cli,
	}
}

func (m *defaultBlockMonitor) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := NewBlockMonitorClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
