// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package blockMonitor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlockMonitorClient is the client API for BlockMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockMonitorClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type blockMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockMonitorClient(cc grpc.ClientConnInterface) BlockMonitorClient {
	return &blockMonitorClient{cc}
}

func (c *blockMonitorClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/blockMonitor.BlockMonitor/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockMonitorServer is the server API for BlockMonitor service.
// All implementations must embed UnimplementedBlockMonitorServer
// for forward compatibility
type BlockMonitorServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedBlockMonitorServer()
}

// UnimplementedBlockMonitorServer must be embedded to have forward compatible implementations.
type UnimplementedBlockMonitorServer struct {
}

func (UnimplementedBlockMonitorServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBlockMonitorServer) mustEmbedUnimplementedBlockMonitorServer() {}

// UnsafeBlockMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockMonitorServer will
// result in compilation errors.
type UnsafeBlockMonitorServer interface {
	mustEmbedUnimplementedBlockMonitorServer()
}

func RegisterBlockMonitorServer(s grpc.ServiceRegistrar, srv BlockMonitorServer) {
	s.RegisterService(&BlockMonitor_ServiceDesc, srv)
}

func _BlockMonitor_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockMonitorServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockMonitor.BlockMonitor/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockMonitorServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// BlockMonitor_ServiceDesc is the grpc.ServiceDesc for BlockMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlockMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blockMonitor.BlockMonitor",
	HandlerType: (*BlockMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _BlockMonitor_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "governanceMonitor.proto",
}
