// Code generated by goctl. DO NOT EDIT.
package types

type ReqGetStatus struct {
}

type RespGetStatus struct {
	Status    uint32 `json:"status"`
	NetworkId uint32 `json:"network_id"`
}

type ReqGetLayer2BasicInfo struct {
}

type RespGetLayer2BasicInfo struct {
	BlockCommitted             int64    `json:"block_committed"`
	BlockVerified              int64    `json:"block_verified"`
	TotalTransactions          int64    `json:"total_transactions"`
	TransactionsCountYesterday int64    `json:"transactions_count_yesterday"`
	TransactionsCountToday     int64    `json:"transactions_count_today"`
	DauYesterday               int64    `json:"dau_yesterday"`
	DauToday                   int64    `json:"dau_today"`
	ContractAddresses          []string `json:"contract_addresses"`
}

type ReqGetAssetsList struct {
}

type Asset struct {
	AssetId       int64  `json:"asset_id"`
	AssetAddr     string `json:"asset_addr"`
	AssetDecimals int64  `json:"asset_decimals"`
	AssetSymbol   string `json:"asset_symbol"`
}

type RespGetAssetsList struct {
	Assets []*Asset `json:"assets"`
}

type ReqSearch struct {
	Info string `form:"info"`
}

type RespSearch struct {
	DataType int32 `json:"data_type"`
}

type ReqGetAccounts struct {
	Offset uint16 `form:"offset" validator:"min=0"`
	Limit  uint16 `form:"limit" validator:"min=0,max=50"`
}

type Accounts struct {
	AccountIndex uint32 `json:"account_index"`
	AccountName  string `json:"account_name"`
	PublicKey    string `json:"public_key"`
}

type RespGetAccounts struct {
	Total    uint32      `json:"total"`
	Accounts []*Accounts `json:"accounts"`
}

type TxHash struct {
	TxHash    string `json:"tx_hash"`
	CreatedAt int64  `json:"created_at"`
}

type Block struct {
	BlockCommitment                 string `json:"block_commitment"`
	BlockHeight                     int64  `json:"block_height"`
	StateRoot                       string `json:"state_root"`
	PriorityOperations              int64  `json:"priority_operations"`
	PendingOnChainOperationsHash    string `json:"pending_on_chain_operations_hash"`
	PendingOnChainOperationsPubData string `json:"pending_on_chain_operations_hub_data"`
	CommittedTxHash                 string `json:"committed_tx_hash"`
	CommittedAt                     int64  `json:"committed_at"`
	VerifiedTxHash                  string `json:"verified_tx_hash"`
	VerifiedAt                      int64  `json:"verified_at"`
	Txs                             []*Tx  `json:"txs"`
	BlockStatus                     int64  `json:"block_status"`
}

type ReqGetBlocks struct {
	Offset uint16 `form:"offset"`
	Limit  uint16 `form:"limit"`
}

type RespGetBlocks struct {
	Total  uint32   `json:"total"`
	Blocks []*Block `json:"blocks"`
}

type ReqGetBlockByCommitment struct {
	BlockCommitment string `form:"block_commitment"`
}

type RespGetBlockByCommitment struct {
	Block Block `json:"block"`
}

type ReqGetBlockByBlockHeight struct {
	BlockHeight uint64 `form:"block_height"`
}

type RespGetBlockByBlockHeight struct {
	Block Block `json:"block"`
}

type Tx struct {
	TxHash        string      `json:"tx_hash"`
	TxType        int64       `json:"tx_type"`
	GasFee        string      `json:"gas_fee"`
	GasFeeAssetId int64       `json:"gas_fee_asset_id"`
	TxStatus      int64       `json:"tx_status"`
	BlockHeight   int64       `json:"block_height"`
	BlockId       int64       `json:"block_id"`
	StateRoot     string      `json:"state_root"`
	NftIndex      int64       `json:"nft_index"`
	PairIndex     int64       `json:"pair_index"`
	AssetId       int64       `json:"asset_id"`
	TxAmount      string      `json:"tx_amount"`
	NativeAddress string      `json:"native_address"`
	TxInfo        string      `json:"tx_info"`
	TxDetails     []*TxDetail `json:"tx_details"`
	ExtraInfo     string      `json:"extra_info"`
	Memo          string      `json:"memo"`
	AccountIndex  int64       `json:"account_index"`
	Nonce         int64       `json:"nonce"`
	ExpiredAt     int64       `json:"expired_at"`
	CreatedAt     int64       `json:"created_at"`
}

type TxDetail struct {
	TxId            int64  `json:"tx_id"`
	AssetId         int64  `json:"asset_id"`
	AssetType       int64  `json:"asset_type"`
	AccountIndex    int64  `json:"account_index"`
	AccountName     string `json:"account_name"`
	Balance         string `json:"balance"`
	BalanceDelta    string `json:"balance_delta"`
	Order           int64  `json:"order"`
	AccountOrder    int64  `json:"account_order"`
	Nonce           int64  `json:"nonce"`
	CollectionNonce int64  `json:"collection_nonce"`
}

type ReqGetTxsListByBlockHeight struct {
	BlockHeight uint64 `form:"block_height"`
	Limit       uint16 `form:"limit"`
	Offset      uint16 `form:"offset"`
}

type RespGetTxsListByBlockHeight struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"txs"`
}

type ReqGetTxByHash struct {
	TxHash string `form:"tx_hash"`
}

type RespGetTxByHash struct {
	Txs      Tx    `json:"result"`
	AssetAId int64 `json:"asset_a_id"`
	AssetBId int64 `json:"asset_b_id"`
}

type ReqGetTxsListByAccountIndex struct {
	AccountIndex uint32 `form:"account_index"`
	Offset       uint16 `form:"offset"`
	Limit        uint16 `form:"limit"`
}

type RespGetTxsListByAccountIndex struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"txs"`
}

type ReqGetMempoolTxsList struct {
	Offset uint16 `form:"offset"`
	Limit  uint16 `form:"limit"`
}

type RespGetMempoolTxsList struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"txs"`
}

type ReqGetMempoolTxsListByPublicKey struct {
	AccountPk string `form:"account_pk"`
	Offset    uint16 `form:"offset"`
	Limit     uint16 `form:"limit"`
}

type RespGetMempoolTxsListByPublicKey struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"data"`
}

type ReqGetmempoolTxsByAccountName struct {
	AccountName string `form:"account_name"`
}

type RespGetmempoolTxsByAccountName struct {
	Total uint32 `json:"total"`
	Txs   []*Tx  `json:"data"`
}

type ReqSendTx struct {
	TxType uint32 `form:"tx_type"`
	TxInfo string `form:"tx_info"`
}

type RespSendTx struct {
	TxId string `json:"tx_id"`
}

type AssetInfo struct {
	AssetId uint32 `json:"assetId"`
	Balance string `json:"balance"`
}

type ReqGetAccountInfoByAccountName struct {
	AccountName string `form:"account_name"`
}

type RespGetAccountInfoByAccountName struct {
	AccountIndex uint32       `json:"account_index"`
	AccountPk    string       `json:"account_pk"`
	Assets       []*AssetInfo `json:"assets"`
}

type ReqGetAccountInfoByPubKey struct {
	AccountPk string `form:"account_pk"`
}

type RespGetAccountInfoByPubKey struct {
	AccountIndex uint32       `json:"account_index"`
	AccountName  string       `form:"account_name"`
	Assets       []*AssetInfo `json:"assets"`
}

type ReqGetMaxOfferId struct {
	AccountIndex uint32 `form:"account_index"`
}

type RespGetMaxOfferId struct {
	OfferId uint64 `json:"offer_id"`
}
