// Code generated by MockGen. DO NOT EDIT.
// Source: api.go

// Package commglobalmap is a generated GoMock package.
package commglobalmap

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	commonAsset "github.com/zecrey-labs/zecrey-legend/common/commonAsset"
	globalmapHandler "github.com/zecrey-labs/zecrey-legend/common/util/globalmapHandler"
)

// MockCommglobalmap is a mock of Commglobalmap interface.
type MockCommglobalmap struct {
	ctrl     *gomock.Controller
	recorder *MockCommglobalmapMockRecorder
}

// MockCommglobalmapMockRecorder is the mock recorder for MockCommglobalmap.
type MockCommglobalmapMockRecorder struct {
	mock *MockCommglobalmap
}

// NewMockCommglobalmap creates a new mock instance.
func NewMockCommglobalmap(ctrl *gomock.Controller) *MockCommglobalmap {
	mock := &MockCommglobalmap{ctrl: ctrl}
	mock.recorder = &MockCommglobalmapMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommglobalmap) EXPECT() *MockCommglobalmapMockRecorder {
	return m.recorder
}

// DeleteLatestAccountInfoInCache mocks base method.
func (m *MockCommglobalmap) DeleteLatestAccountInfoInCache(ctx context.Context, accountIndex int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLatestAccountInfoInCache", ctx, accountIndex)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLatestAccountInfoInCache indicates an expected call of DeleteLatestAccountInfoInCache.
func (mr *MockCommglobalmapMockRecorder) DeleteLatestAccountInfoInCache(ctx, accountIndex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLatestAccountInfoInCache", reflect.TypeOf((*MockCommglobalmap)(nil).DeleteLatestAccountInfoInCache), ctx, accountIndex)
}

// GetBasicAccountInfo mocks base method.
func (m *MockCommglobalmap) GetBasicAccountInfo(ctx context.Context, accountIndex int64) (*commonAsset.AccountInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBasicAccountInfo", ctx, accountIndex)
	ret0, _ := ret[0].(*commonAsset.AccountInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasicAccountInfo indicates an expected call of GetBasicAccountInfo.
func (mr *MockCommglobalmapMockRecorder) GetBasicAccountInfo(ctx, accountIndex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasicAccountInfo", reflect.TypeOf((*MockCommglobalmap)(nil).GetBasicAccountInfo), ctx, accountIndex)
}

// GetLatestAccountInfo mocks base method.
func (m *MockCommglobalmap) GetLatestAccountInfo(ctx context.Context, accountIndex int64) (*commonAsset.AccountInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestAccountInfo", ctx, accountIndex)
	ret0, _ := ret[0].(*commonAsset.AccountInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestAccountInfo indicates an expected call of GetLatestAccountInfo.
func (mr *MockCommglobalmapMockRecorder) GetLatestAccountInfo(ctx, accountIndex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestAccountInfo", reflect.TypeOf((*MockCommglobalmap)(nil).GetLatestAccountInfo), ctx, accountIndex)
}

// GetLatestAccountInfoWithCache mocks base method.
func (m *MockCommglobalmap) GetLatestAccountInfoWithCache(ctx context.Context, accountIndex int64) (*commonAsset.AccountInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestAccountInfoWithCache", ctx, accountIndex)
	ret0, _ := ret[0].(*commonAsset.AccountInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestAccountInfoWithCache indicates an expected call of GetLatestAccountInfoWithCache.
func (mr *MockCommglobalmapMockRecorder) GetLatestAccountInfoWithCache(ctx, accountIndex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestAccountInfoWithCache", reflect.TypeOf((*MockCommglobalmap)(nil).GetLatestAccountInfoWithCache), ctx, accountIndex)
}

// GetLatestLiquidityInfoForRead mocks base method.
func (m *MockCommglobalmap) GetLatestLiquidityInfoForRead(ctx context.Context, pairIndex int64) (*globalmapHandler.LiquidityInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestLiquidityInfoForRead", ctx, pairIndex)
	ret0, _ := ret[0].(*globalmapHandler.LiquidityInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestLiquidityInfoForRead indicates an expected call of GetLatestLiquidityInfoForRead.
func (mr *MockCommglobalmapMockRecorder) GetLatestLiquidityInfoForRead(ctx, pairIndex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestLiquidityInfoForRead", reflect.TypeOf((*MockCommglobalmap)(nil).GetLatestLiquidityInfoForRead), ctx, pairIndex)
}

// GetLatestLiquidityInfoForReadWithCache mocks base method.
func (m *MockCommglobalmap) GetLatestLiquidityInfoForReadWithCache(ctx context.Context, pairIndex int64) (*globalmapHandler.LiquidityInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestLiquidityInfoForReadWithCache", ctx, pairIndex)
	ret0, _ := ret[0].(*globalmapHandler.LiquidityInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestLiquidityInfoForReadWithCache indicates an expected call of GetLatestLiquidityInfoForReadWithCache.
func (mr *MockCommglobalmapMockRecorder) GetLatestLiquidityInfoForReadWithCache(ctx, pairIndex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestLiquidityInfoForReadWithCache", reflect.TypeOf((*MockCommglobalmap)(nil).GetLatestLiquidityInfoForReadWithCache), ctx, pairIndex)
}

// GetLatestOfferIdForWrite mocks base method.
func (m *MockCommglobalmap) GetLatestOfferIdForWrite(ctx context.Context, accountIndex int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestOfferIdForWrite", ctx, accountIndex)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestOfferIdForWrite indicates an expected call of GetLatestOfferIdForWrite.
func (mr *MockCommglobalmapMockRecorder) GetLatestOfferIdForWrite(ctx, accountIndex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestOfferIdForWrite", reflect.TypeOf((*MockCommglobalmap)(nil).GetLatestOfferIdForWrite), ctx, accountIndex)
}
