package errorcode

import (
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

// using method:
// err := error.New(10000, "Example error msg")
// fmt.Println("err:", err.Sprintf())
// error code in [10000,20000) represent business error
// error code in [20000,30000) represent logic layer error
// error code in [30000,40000) represent repo layer error

//TODO: need to go through each error code, current definition is not good

var (
	//repo (db & cache)

	RepoErrNotFound               = New(30000, sqlx.ErrNotFound.Error())
	RepoErrSqlOperation           = New(30001, "Sql operation")
	RepoErrToFormatAccountInfo    = New(30002, "Err ToFormatAccountInfo")
	RepoErrFromFormatAccountInfo  = New(30003, "Err FromFormatAccountInfo")
	RepoErrComputeNewBalance      = New(30004, "Err ComputeNewBalance")
	RepoErrParseAccountAsset      = New(30005, "Err ParseAccountAsset")
	RepoErrParseInt               = New(30006, "Err ParseInt")
	RepoErrInvalidAssetType       = New(30007, "Invalid asset type")
	RepoErrConstructLiquidityInfo = New(30008, "Err ConstructLiquidityInfo")
	RepoErrParseLiquidityInfo     = New(30009, "Err ParseLiquidityInfo")
	RepoErrParseNftInfo           = New(30010, "Err ParseNftInfo")
	RepoErrInvalidFailTx          = New(30011, "Err invalid fail txVerification")

	RepoErrDataNotExist     = New(30000, "Data not exist")
	RepoErrInvalidSysconfig = New(30002, "Invalid system config")
	RepoErrTypeAsset        = New(30003, "Err TypeAsset")
	RepoErrQuoteNotExist    = New(30004, "Err QuoteNotExist")
	RepoErrNewHttpRequest   = New(30005, "http.NewRequest err")
	RepoErrHttpClientDo     = New(30006, "http.Client.Do err")
	RepoErrIoutilReadAll    = New(30007, "ioutil.ReadAll err")
	RepoErrJsonUnmarshal    = New(30008, "json.Unmarshal err")
	RepoErrJsonMarshal      = New(30009, "json.Marshal err")
	RepoErrTypeAssertion    = New(30010, "type assertion err")

	// error generated by multcache
	CacheErrGet = New(40000, "Err CacheGet")
	CacheErrSet = New(40001, "Err CacheSet")
	CacheErrDel = New(40002, "Err CacheDel")

	//others

	//global rpc

	GlobalRpcInvalidParam              = New(20000, "invalid param")
	GlobalRpcErrInvalidTxType          = New(20001, "invalid tx type")
	GlobalRpcErrInvalidGasFee          = New(20002, "invalid gas fee")
	GlobalRpcErrInvalidAmount          = New(20003, "invalid amount")
	GlobalRpcErrInvalidAsset           = New(20004, "AssetA or AssetB is 0 in the liquidity Table")
	GlobalRpcErrInvalidAssetID         = New(20005, "invalid pair assetId")
	GlobalRpcErrInvalidGasAccountIndex = New(20006, "invalid GasAccountIndex")
	GlobalRpcErrInvalidExpiredAt       = New(20007, "invalid ExpiredAt")
	GlobalRpcErrInvalidLiquidityAsset  = New(20008, "invalid LiquidityAsset")
	GlobalRpcErrMarshal                = New(20009, "marshal error")
	GlobalRpcErrCreateFailTx           = New(20010, "fail to create tx")

	GlobalRpcErrNotFound    = New(24404, "not found")
	GlobalRpcErrInternalErr = New(24500, "internal server error")

	//app service

	AppErrInvalidParam = New(25000, "invalid param")

	AppErrNotFound    = New(29404, "not found")
	AppErrInternalErr = New(29500, "internal server error")
)
